# Generated by Django 3.2.6 on 2022-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
