# Generated by Django 3.2.6 on 2022-05-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='vendor/img/users/default_avatar.jpg', upload_to='product_images'),
        ),
    ]
