# Generated by Django 3.2.6 on 2022-05-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_userprofile_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lang',
            new_name='langs',
        ),
    ]
